apiVersion: v1
kind: PersistentVolume
metadata:
  name: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /database/


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: eveigadev/projeto-database:1.0
        args:
        - "--ignore-db-dir=lost+found"
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql

        volumeMounts:
        - name: local
          mountPath: /var/lib/mysql/
      volumes:
      - name: local
        hostPath:
          path: /database/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: eveigadev/projeto-backend:1.0
        #imagePullPolicy: Always
        ports:
        - containerPort: 80

