apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-html-deploy
  labels:
    app: app-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-html
  template:
    metadata:
      labels:
        app: app-html
    spec:
      containers:
      - name: app-html
        image: httpd
        ports:
        - containerPort: 80
